[build]
base = "heart-rate-drift/"
publish = "heart-rate-drift/dist/"
command = "trunk build"

[dev]
command = "trunk serve --config ./heart-rate-drift/trunk.toml"
framework = "#static"

[functions]
directory = "netlify/functions"
