[build]
command = "trunk build --config ./heart-rate-drift/trunk.toml"

[context.production]
NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true"

[dev]
command = "trunk serve --config ./heart-rate-drift/trunk.toml"
framework = "#static"

[functions] 
directory = "./netlify/functions"


