[package]
name = "get-strava-activity"
version = "0.1.0"
edition = "2018"

[dependencies]
aws_lambda_events = "0.15.0"
http = "1.2.0"
hyper-util = "0.1.10"
lambda_runtime = "0.13.0"
log = "0.4.17"
simple_logger = "1.16.0"
tokio = "1.27.0"
